
CREATE USER `DB_USER`@`localhost` IDENTIFIED BY 'PASSWORD';
CREATE USER `DB_USER`@`127.0.0.1` IDENTIFIED BY 'PASSWORD';

GRANT ALL PRIVILEGES ON `DB_NAME`.* TO `DB_USER`@`localhost`;
GRANT ALL PRIVILEGES ON `DB_NAME`.* TO `DB_USER`@`127.0.0.1`;

CREATE DATABASE IF NOT EXISTS `DB_NAME` DEFAULT CHARACTER SET utf8;